#pragma once

#include "Common/CommonTypes.h"
#include "GBAStation/PpssppGBAStationConfig.h"
#include "GBAStation/GBAStationConfig.h"
#include "GBAStation/GBAStationCoreConfig.h"

#include <array>
#include <cstddef>
#include <ctime>
#include <string>
#include <vector>

struct ImGuiContext;
struct ImDrawList;
struct ImVec2;

namespace Draw {
class DrawContext;
class Texture;
}

namespace GBAStation {

enum class OverlayAction {
	None,
	SaveState,
	LoadState,
	Reset,
	LoadCheats,
	ToggleCheat,
};

struct OverlayCommand {
	OverlayAction action = OverlayAction::None;
	int slot = 0;
};

enum class CheatMenuEntryKind {
	Cheat,
	Section,
	Tip,
};

struct CheatMenuEntry {
	std::string name;
	bool enabled = false;
	bool toggleable = true;
	int sourceIndex = -1;
	CheatMenuEntryKind kind = CheatMenuEntryKind::Cheat;
};

class Overlay {
public:
	bool Init(Draw::DrawContext *draw, const char *gamePath, LogCallback log = {});
	void Shutdown();

	// menuTogglePressed is generated by the GBAStation config.cfg binding.  Do
	// not infer it from physical Plus+Minus here: that was the old GBAStation hotkey.
	bool HandleInput(u64 buttons, u64 pressed, int leftStickX, int leftStickY, int rightStickX, int rightStickY,
		bool menuTogglePressed);
	void Render(Draw::DrawContext *draw);
	void SetSaveStateInfo(int currentSlot, const std::array<bool, Ppsspp::SaveStateSlotCount> &slotInUse,
		const std::array<time_t, Ppsspp::SaveStateSlotCount> &slotMtime = {});
	void SetCheatsEnabled(bool enabled);
	void SetCheatInfo(bool enabled, bool available, const std::vector<CheatMenuEntry> &entries);
	void ReloadDisplaySettings();

	bool IsReady() const { return ready_; }
	bool IsVisible() const { return visible_; }
	bool ConsumeCoreSettingsChanged() {
		const bool changed = coreSettingsChanged_;
		coreSettingsChanged_ = false;
		return changed;
	}
	bool ShouldExitGame() const { return exitRequested_; }
	void ClearExitRequest() { exitRequested_ = false; }
	OverlayCommand ConsumeCommand();
	void SetVisible(bool visible);

private:
	enum class Menu {
		Quick,
		SaveStates,
		Cheats,
		Settings,
	};

	int ItemCount() const;
	int QuickMenuStorageIndex(int visibleIndex) const;
	void DrawUI(float width, float height, float deltaTime);
	void DrawBackground(::ImDrawList *drawList, ::ImVec2 displaySize, float ease);
	void DrawMenu(::ImDrawList *drawList, ::ImVec2 displaySize, float scale, float ease);
	void DrawHelpers(::ImDrawList *drawList, ::ImVec2 displaySize, float scale, float ease);
	void DrawRAAlerts(Draw::DrawContext *draw, ::ImDrawList *drawList, ::ImVec2 displaySize, float scale, float deltaTime);
	void CycleSetting(int direction);
	void ActivateTab(int tab);
	void ApplyDisplaySettings(bool save);
	Draw::Texture *LoadRAIconTexture(Draw::DrawContext *draw);
	void ReleaseRAIconTexture();
	void LoadFocusTexture(Draw::DrawContext *draw);
	void ReleaseFocusTexture();
	void DrawFlowBorder(::ImDrawList *drawList, float x, float y, float w, float h, float thickness);
	void ExecuteSelection();

	LogCallback log_;
	bool ready_ = false;
	bool visible_ = false;
	bool comboDown_ = false;
	bool exitRequested_ = false;
	int selection_ = 0;
	int tabSelection_ = 0;
	bool sidebarFocused_ = true;
	int settingsSelection_ = 0;
	bool coreSettingsPage_ = false;
	bool coreSettingsChanged_ = false;
	Menu menu_ = Menu::Quick;
	OverlayAction saveStateMode_ = OverlayAction::SaveState;
	DisplaySettings displaySettings_;
	OverlayCommand pendingCommand_;
	int currentStateSlot_ = 0;
	std::array<bool, Ppsspp::SaveStateSlotCount> slotInUse_{};
	std::array<time_t, Ppsspp::SaveStateSlotCount> slotMtime_{};
	bool cheatsEnabled_ = false;
	bool cheatsAvailable_ = false;
	bool cheatsLoading_ = false;
	bool cheatsLoadCommandSent_ = false;
	int cheatsLoadingDelayFrames_ = 0;
	std::vector<CheatMenuEntry> cheats_;
	u64 lastAnalogNavMs_ = 0;
	u64 lastDPadNavMs_ = 0;
	// 3DS-style d-pad repeat: first repeat waits 280 ms, then speeds up.
	static constexpr u64 kDPadNavInitialRepeatMs = 280;
	int dpadNavDir_ = 0;
	u64 nextDPadNavMs_ = 0;
	u64 dpadNavStartMs_ = 0;
	u64 nextCheatVerticalNavMs_ = 0;
	u64 nextCheatHorizontalNavMs_ = 0;
	int cheatVerticalNavDir_ = 0;
	int cheatHorizontalNavDir_ = 0;
	float animTimer_ = 0.0f;
	std::string title_;
	Draw::Texture *raIconTexture_ = nullptr;
	Draw::Texture *focusTexture_ = nullptr;
	ImGuiContext *context_ = nullptr;
};

}  // namespace GBAStation
