#pragma once

#include "Common/CommonTypes.h"
#include "GBAStation/PpssppGBAStationConfig.h"
#include "GBAStation/GBAStationConfig.h"
#include "GBAStation/GBAStationCoreConfig.h"

#include <array>
#include <cstddef>
#include <ctime>
#include <string>
#include <vector>

struct ImGuiContext;
struct ImDrawList;
struct ImVec2;

namespace Draw {
class DrawContext;
class Texture;
}

namespace GBAStation {

enum class OverlayAction {
	None,
	SaveState,
	LoadState,
	Reset,
	LoadCheats,
	ToggleCheat,
};

struct OverlayCommand {
	OverlayAction action = OverlayAction::None;
	int slot = 0;
};

enum class CheatMenuEntryKind {
	Cheat,
	Section,
	Tip,
};

struct CheatMenuEntry {
	std::string name;
	bool enabled = false;
	bool toggleable = true;
	int sourceIndex = -1;
	CheatMenuEntryKind kind = CheatMenuEntryKind::Cheat;
};

class Overlay {
public:
	bool Init(Draw::DrawContext *draw, const char *gamePath, LogCallback log = {});
	Draw::DrawContext *draw_ = nullptr;
	void Shutdown();

	// menuTogglePressed is generated by the GBAStation config.cfg binding.  Do
	// not infer it from physical Plus+Minus here: that was the old GBAStation hotkey.
	bool HandleInput(u64 buttons, u64 pressed, int leftStickX, int leftStickY, int rightStickX, int rightStickY,
		bool menuTogglePressed);
	void Render(Draw::DrawContext *draw);
	// Load/refresh slot thumbnail textures outside the render frame (thin3d
	// texture creation must not happen mid-ImGui-frame).
	void RefreshSlotThumbs(Draw::DrawContext *draw);
	void SetSaveStateInfo(int currentSlot, const std::array<bool, Ppsspp::SaveStateSlotCount> &slotInUse,
		const std::array<time_t, Ppsspp::SaveStateSlotCount> &slotMtime = {});
	void SetCheatsEnabled(bool enabled);
	void SetCheatInfo(bool enabled, bool available, const std::vector<CheatMenuEntry> &entries);
	void ReloadDisplaySettings();
	// Per-title display values come from the launcher GameDB.  Keep them in the
	// overlay rather than reloading the global core config whenever the menu is
	// opened, otherwise one game's aspect/scale leaks into the next game.
	void SetGameDisplaySettings(int displayMode, const std::string &screenLayout, int internalResolution,
		float customScale = 1.0f, float customOffsetX = 0.5f, float customOffsetY = 0.5f);
	void SetGameMaskSettings(bool enabled, const std::string &path);
	bool IsGameMaskEnabled() const { return gameMaskEnabled_; }
	const std::string &GameMaskPath() const { return gameMaskPath_; }
	void SetGameShaderSettings(bool enabled, const std::string &section);
	bool IsGameShaderEnabled() const { return gameShaderEnabled_; }
	const std::string &GameShaderSection() const { return gameShaderSection_; }
	// These requests are deliberately one-shot.  The runtime owns GameDB and
	// applies a confirmed request to every *other* PSP entry.
	bool ConsumeSyncDisplaySettingsRequest();
	bool ConsumeSyncMaskSettingsRequest();
	bool ConsumeSyncShaderSettingsRequest();
	bool ConsumeGameDisplaySettingsSaveRequest() {
		const bool requested = gameDisplaySettingsSaveRequested_;
		gameDisplaySettingsSaveRequested_ = false;
		return requested;
	}
	bool ConsumeGameShaderSettingsSaveRequest() {
		const bool requested = gameShaderSettingsSaveRequested_;
		gameShaderSettingsSaveRequested_ = false;
		return requested;
	}
	int GameDisplayModeIndex() const { return static_cast<int>(displaySettings_.mode); }
	const char *GameScreenLayout() const { return DisplaySizeLabel(displaySettings_.size); }
	float GameCustomDisplayScale() const { return displaySettings_.customScale; }
	float GameCustomDisplayOffsetX() const { return displaySettings_.customOffsetX; }
	float GameCustomDisplayOffsetY() const { return displaySettings_.customOffsetY; }

	bool IsReady() const { return ready_; }
	bool IsVisible() const { return visible_; }
	bool ConsumeCoreSettingsChanged() {
		const bool changed = coreSettingsChanged_;
		coreSettingsChanged_ = false;
		return changed;
	}
	bool ShouldExitGame() const { return exitRequested_; }
	void ClearExitRequest() { exitRequested_ = false; }
	// The runtime keeps the menu alive while the configured exit savestate and
	// its thumbnail are written.  This state deliberately consumes all input.
	void SetExitSaving(bool saving, bool waitingForNativeSave = false);
	OverlayCommand ConsumeCommand();
	void SetVisible(bool visible);

private:
	enum class Menu {
		Quick,
		SaveStates,
		Cheats,
		Settings,
	};
	enum class SettingsSidebar {
		None,
		Mask,
		Shader,
		Custom,
		MaskPicker,
		ShaderPicker,
	};
	struct PickerEntry {
		std::string label;
		std::string path;
		bool directory = false;
	};
	enum class SyncConfirm {
		None,
		Display,
		Mask,
		Shader,
	};

	int ItemCount() const;
	int QuickMenuStorageIndex(int visibleIndex) const;
	void DrawUI(float width, float height, float deltaTime);
	void DrawHud(::ImDrawList *drawList, float width, float height);
	void DrawBackground(::ImDrawList *drawList, ::ImVec2 displaySize, float ease);
	void DrawMenu(::ImDrawList *drawList, ::ImVec2 displaySize, float scale, float ease);
	void DrawHelpers(::ImDrawList *drawList, ::ImVec2 displaySize, float scale, float ease);
	void DrawRAAlerts(Draw::DrawContext *draw, ::ImDrawList *drawList, ::ImVec2 displaySize, float scale, float deltaTime);
	void DrawSyncConfirmDialog(::ImDrawList *drawList, ::ImVec2 displaySize, float scale, float ease);
	void DrawExitSavingDialog(::ImDrawList *drawList, ::ImVec2 displaySize, float scale, float ease);
	void DrawSettingsSidebar(::ImDrawList *drawList, ::ImVec2 displaySize, float scale, float ease);
	void CycleSetting(int direction);
	void OpenSettingsSidebar(SettingsSidebar sidebar);
	void ReloadPickerEntries();
	bool HandleSettingsSidebarInput(u64 buttons, u64 pressed, bool navUp, bool navDown, bool navLeft, bool navRight);
	void ActivateTab(int tab);
	void ApplyDisplaySettings(bool save);
	Draw::Texture *LoadRAIconTexture(Draw::DrawContext *draw);
	void ReleaseRAIconTexture();
	void LoadFocusTexture(Draw::DrawContext *draw);
	void ReleaseFocusTexture();
	void LoadMaskTexture(Draw::DrawContext *draw);
	void ReleaseMaskTexture();
	void DrawFlowBorder(::ImDrawList *drawList, float x, float y, float w, float h, float thickness);
	void ExecuteSelection();

	LogCallback log_;
	bool ready_ = false;
	bool visible_ = false;
	bool comboDown_ = false;
	bool exitRequested_ = false;
	bool exitSaving_ = false;
	bool exitWaitingForNativeSave_ = false;
	int selection_ = 0;
	int tabSelection_ = 0;
	bool sidebarFocused_ = true;
	int settingsSelection_ = 0;
	bool coreSettingsPage_ = false;
	bool coreSettingsChanged_ = false;
	bool gameDisplaySettingsSaveRequested_ = false;
	bool gameShaderSettingsSaveRequested_ = false;
	bool syncDisplaySettingsRequested_ = false;
	bool syncMaskSettingsRequested_ = false;
	bool syncShaderSettingsRequested_ = false;
	SyncConfirm syncConfirm_ = SyncConfirm::None;
	SettingsSidebar settingsSidebar_ = SettingsSidebar::None;
	int sidebarSelection_ = 0;
	int sidebarAdjustDir_ = 0;
	u64 sidebarAdjustStartMs_ = 0;
	u64 sidebarAdjustNextMs_ = 0;
	std::vector<PickerEntry> pickerEntries_;
	std::string pickerDirectory_;
	bool hasGameDisplaySettings_ = false;
	Menu menu_ = Menu::Quick;
	OverlayAction saveStateMode_ = OverlayAction::SaveState;
	DisplaySettings displaySettings_;
	OverlayCommand pendingCommand_;
	int currentStateSlot_ = 0;
	std::array<bool, Ppsspp::SaveStateSlotCount> slotInUse_{};
	std::array<time_t, Ppsspp::SaveStateSlotCount> slotMtime_{};
	// Cached slot thumbnails (thin3d texture + state mtime).
	struct SlotThumb {
		Draw::Texture *tex = nullptr;
		time_t mtime = 0;
	};
	std::array<SlotThumb, Ppsspp::SaveStateSlotCount> slotThumbs_{};
	bool cheatsEnabled_ = false;
	bool cheatsAvailable_ = false;
	bool cheatsLoading_ = false;
	bool cheatsLoadCommandSent_ = false;
	int cheatsLoadingDelayFrames_ = 0;
	std::vector<CheatMenuEntry> cheats_;
	u64 lastAnalogNavMs_ = 0;
	u64 lastDPadNavMs_ = 0;
	// 3DS-style d-pad repeat: first repeat waits 280 ms, then speeds up.
	static constexpr u64 kDPadNavInitialRepeatMs = 360;
	int dpadNavDir_ = 0;
	u64 nextDPadNavMs_ = 0;
	u64 dpadNavStartMs_ = 0;
	// LR selectors use their own repeat track so settings can be adjusted
	// smoothly without accelerating general menu navigation.
	int selectorAdjustDir_ = 0;
	u64 selectorAdjustStartMs_ = 0;
	u64 selectorAdjustNextMs_ = 0;
	u64 nextCheatVerticalNavMs_ = 0;
	u64 nextCheatHorizontalNavMs_ = 0;
	int cheatVerticalNavDir_ = 0;
	int cheatHorizontalNavDir_ = 0;
	float animTimer_ = 0.0f;
	std::string title_;
	Draw::Texture *raIconTexture_ = nullptr;
	Draw::Texture *focusTexture_ = nullptr;
	Draw::Texture *maskTexture_ = nullptr;
	// A texture may still be referenced by a submitted ImGui draw list when a
	// GameDB mask is changed.  Keep replaced textures alive until Shutdown
	// rather than releasing an in-flight Thin3D resource.
	std::vector<Draw::Texture *> retiredMaskTextures_;
	bool gameMaskEnabled_ = false;
	std::string gameMaskPath_;
	bool gameShaderEnabled_ = false;
	std::string gameShaderSection_;
	ImGuiContext *context_ = nullptr;
};

}  // namespace GBAStation
